export const BeerStyles = [
  { label: 'IPA', value: 'ipa' },
  { label: 'Hazy IPA', value: 'hazy-ipa' },
  { label: 'Double IPA', value: 'double-ipa' },
  { label: 'Pale Ale', value: 'pale-ale' },
  { label: 'Hazy Pale Ale', value: 'hazy-pale-ale' },
  { label: 'Bitter', value: 'bitter' },
  { label: 'Special Bitter', value: 'special-bitter' },
  { label: 'Extra Special Bitter', value: 'extra-special-bitter' },
  { label: 'Scottish Ale', value: 'scottish-ale' },
  { label: 'Brown Porter', value: 'brown-porter' },
  { label: 'Porter', value: 'porter' },
  { label: 'Imperial Stout', value: 'imperial-stout' },
  { label: 'Stout', value: 'stout' },
  { label: 'Oatmeal Stout', value: 'oatmeal-stout' },
  { label: 'Golden ale', value: 'golden-ale' },
  { label: 'Session IPA', value: 'session-ipa' },
  { label: 'Amber Ale', value: 'amber-ale' },
  { label: 'Brown Ale', value: 'brown-ale' },
  { label: 'Lager', value: 'lager' },
  { label: 'Sour', value: 'sour' },
  { label: 'Blonde Ale', value: 'blonde-ale' },
  { label: 'Dubbel', value: 'dubbel' },
  { label: 'Tripel', value: 'tripel' },
  { label: 'Quadrupel', value: 'quadrupel' },
  { label: 'Saison', value: 'saison' },
  { label: 'Pilsner', value: 'pilsner' },
  { label: 'Hefeweizen', value: 'hefeweizen' },
  { label: 'Kölsch', value: 'kolsch' },
  { label: 'Helles', value: 'helles' },
];
